import streamlit as st

# NOT my own opinion !
# ----------------------------------------------------------------------------------------------------------------------------------------

st.markdown("<h1 style='text-align: center; color : #E8570E; font-size:65px'>The Best</h1>", unsafe_allow_html=True)
st.markdown("<br><hr>", unsafe_allow_html=True)

tabs1, tabs2, tabs3, tabs4, tabs5, tabs6, tabs7, tabs8, tabs9, tabs10 = st.tabs(['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])

with tabs1:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>Google Pixel 7 - Best for most people</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/10/Google-Pixel-7_-review_11.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>We think the best phone for most people is the Google Pixel 7</li><br><li style='font-size:22px;'>It’s the best Pixel phone yet, and has tons of premium features for the frankly incredible price of $599/£599/€649</li><br><li style='font-size:22px;'>For less than the cost of any iPhone 14 or Galaxy S23 model you get a lovely 6.3in 90Hz OLED display, bright and customisable Android 13 software, a premium glass finish with wireless charging and amazingly good main and ultrawide cameras on the back</li><br><li style='font-size:22px;'>That main camera is the best point-and-shoot phone camera on the market, with stunning photos whatever you point it at thanks to the 50Mp sensor and Google’s top level photo processing</li><br><li style='font-size:22px;'>You also get fun software tricks like Magic Eraser to rub out unwanted people or objects from your photos, and other Pixel-exclusive things such as call screening and a call holding feature so you dont have to sit on hold for ages with businesses – though several of these call perks are US-only</li><br><li style='font-size:22px;'>You could opt for the Pixel 7 Pro if you want a bigger screen, better battery life, and an extra optical telephoto zoom lens.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs2:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>iPhone 14 Pro – Best iPhone</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/09/iPhone-14-Pro_review_1.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>The regular iPhone 14 is a very minor update over the iPhone 13, so it’s a pleasant surprise that the iPhone 14 Pro is such a leap over its predecessor</li><br><li style='font-size:22px;'>Some of the change is only skin deep, but when such a visual overhaul as the Dynamic Island makes its debut, it’s hard not to notice</li><br><li style='font-size:22px;'>Apple has shrunk its famous screen notch into a pill and circular shape below the top bezel but filled in the blank space with black pixels, and then used animations to have notifications and updates from apps originate from the space, creating a use for the cut outs now seen for cameras on most phone screens</li><br><li style='font-size:22px;'>It is very clever, and means you can see what music playing, timers, weather and more constantly at the top of the screen without having to hop into the app</li><br><li style='font-size:22px;'>The phone’s cameras are also exceptionally good, with the first 48Mp sensor on an iPhone allowing for 2x zoom cropping in addition to the 3x telephoto lens and a capable ultrawide</li><br><li style='font-size:22px;'>Apple has also finally introduced an always-on display that simply dims your lock screen and pleasingly doesn’t affect battery life, in our testing at least</li><br><li style='font-size:22px;'>It’s not a huge upgrade on the 13 Pro but if your phone is three or four years old this iPhone will feel lightyears into the future.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs3:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>Samsung Galaxy S23 Ultra – The phone with everything</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2023/02/Samsung-Galaxy-S23-Ultra_review_2.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>If you want the phone on the market with the most features possible, the Galaxy S23 Ultra is it</li><br><li style='font-size:22px;'>It’s a big, expensive phone but you get every possible feature you could want in a smartphone in 2023 with incredibly good triple cameras, very good battery life that lasts well over a day, performance as fast as any rival phone, and of course, the now-unique S-Pen stylus tucked away in the phone for when you need it</li><br><li style='font-size:22px;'>It’s one of few phones out there with a squared off body and screen, but it feels good to hold thanks to top build quality and nicely tapered edges and screen</li><br><li style='font-size:22px;'>This design rewards you with the best screen of any phone, perfect for any app you can throw at it, and superlative for watching videos</li><br><li style='font-size:22px;'>The 200Mp main camera is outstanding, particularly if you like slightly saturated colours that pop more than they do in real life</li><br><li style='font-size:22px;'>That’s not to say they look artificial though – the quality is superb with the versatility of an ultrawide and two separate 3x and 10 optical telephoto lenses that are all excellent</li><br><li style='font-size:22px;'>It's a shame the selife camera is terrible in low light.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs4:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>Google Pixel 6a – Best value Android</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/07/Google-Pixel-6A_review_1.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>Although the Pixel 6 and 6 Pro have bigger, better screens and improved cameras, the $449/£399/€459 6a is better value and the Pixel phone most people should buy</li><br><li style='font-size:22px;'>For the asking price you get the Google Tensor chip, the same as the 6 and 6 Pro, resulting in flagship level performance</li><br><li style='font-size:22px;'>Older A-series Pixels were sluggish – not this one</li><br><li style='font-size:22px;'>You only get a 60Hz refresh rate screen, slow 18W charging, and a plastic back that we found scratches quite easily</li><br><li style='font-size:22px;'>There’s also only a 12.2Mp main camera, the same as on the Pixel 5, rather than the Pixel 6’s 50Mp shooter</li><br><li style='font-size:22px;'>But aside from that this is close to the full Pixel experience at a superb price, with three years of Android OS updates and five years of security updates.", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs5:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>OnePlus 11 – Best value flagship</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2023/01/OnePlus-11_review_1.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>OnePlus has nailed the balance with the OnePlus 11, bringing a fully-featured premium smartphone for an outstanding price</li><br><li style='font-size:22px;'>At $699/£729/€849, the only things it noticeably misses out on are wireless charging and full waterproofing (we are more annoyed about the latter than the former)</li><br><li style='font-size:22px;'>If you can forgo those nice-to-haves then you’ll find yourself with a phone that has everything else you could want: amazingly fast performance, an excellent display, strong cameras including a very good main 50Mp lens, and four years of Android updates and five of security updates</li><br><li style='font-size:22px;'>That’s only matched in the Android world by Samsung and Fairphone (iPhones get the longest software support at more than five years)</li><br><li style='font-size:22px;'>The OnePlus 11 is also a slim and svelte phone despite its 6.7in screen, which isn’t the case with other huge phones</li><br><li style='font-size:22px;'>You can go for the green glossy model or the black version that has a matt, almost-silk like finish to the back glass</li><br><li style='font-size:22px;'>It means it gets zero fingerprints, but it’s one of the slipperiest phones out there</li><br><li style='font-size:22px;'>So long as you don’t mind the slight laboured newer version of OxygenOS that often changes Android for change sake, then this is a great phone at a price that ensures you’ll get your money’s worth if you can make it last five years.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs6:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'> iPhone 14 – Superb all-rounder</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/09/iPhone-14-_-review_1.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>The iPhone 14 isn’t as good as the iPhone 14 Pro but it costs less – even if it is pretty much an iPhone 13 with a new name</li><br><li style='font-size:22px;'>The only things of note it adds to the 13 is a very slightly improved main camera and the admittedly impressed stablisation video mode called Action Mode</li><br><li style='font-size:22px;'>There’s also car crash detection, which you will hopefully never have to use – the bottom line is, don’t upgrade from an iPhone 13, but otherwise this is the go-to iPhone for most people right now</li><br><li style='font-size:22px;'>The battery life is excellent and it has great performance, while the cameras are top notch despite not having a telephoto lens</li><br><li style='font-size:22px;'>As ever with Apple, built quality is the best in the business, and iOS is extremely stable software</li><br><li style='font-size:22px;'>You’ll also get software updates for about five years, and can get a repair done at any Apple Store</li><br><li style='font-size:22px;'>If you want a larger screen and more battery, you could opt for the iPhone 14 Plus, but we prefer this smaller model.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs7:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>Samsung Galaxy Z Flip 4 – Best foldable</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/08/Samsung-Galaxy-Watch-5-_review_9-2.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>Samsung has addressed the Z Flip 3’s issues of bad battery life and middling camera performance for the price and made the Z Flip 4 an all-day phone with the same main and ultrawide cameras as the Galaxy S22 and S22 Plus</li><br><li style='font-size:22px;'>It means this is the best foldable phone you can buy today, at a price similar to flagship slab smartphones</li><br><li style='font-size:22px;'>While durability questions remain over the display and the crease in it, we can’t test that – but Samsung says the Flip will last for at least 200,000 open and close motions, which roughly equates to five years of average use</li><br><li style='font-size:22px;'>The improved battery is likely down the Snapdragon 8+ Gen 1 chipset with its improved energy efficiency, meaning you no longer have to charge the Flip halfway through the day</li><br><li style='font-size:22px;'>8GB RAM is more than enough, though you might want to spend a little more to get 256GB storage</li><br><li style='font-size:22px;'>We also love the side mounted fingerprint sensor</li><br><li style='font-size:22px;'>For all intents and purposes, this is an S22 with a better processor that folds down to half its size</li><br><li style='font-size:22px;'>It’s compelling, and one of the best phones full stop.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs8:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>Motorola Moto G62 – Best budget option</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/08/Moto-G62-review-6.jpeg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>The phone that sits atop our best budget phone round up should rightly get a mention as one of the best phones overall – not every great phone has to cost the earth</li><br><li style='font-size:22px;'>The Moto G62 is a sub-£200 handset with all the basics covered – a solid 120Hz screen, attractively simple Android software, very good two-day battery life and a chipset with a processor strong enough to keep up with normal everyday phone tasks (unlike other cheaper phones)</li><br><li style='font-size:22px;'>A 50Mp main camera is also nice to find at this price, but there’s no stablisation tech so you’ll need a steady hand, while the ultrawide and macro lenses aren’t anything to write home about</li><br><li style='font-size:22px;'>But at this price, a camera that takes bright, sharp images in daylight is all you could want</li><br><li style='font-size:22px;'>With 5G built in then you’re set for a few years of use on new networks, though we don’t expect the G62 to get many software updates</li><br><li style='font-size:22px;'>Motorola doesn’t sell this phone in the US, but it sells plenty of equivalent solid Moto phones for around the $200 price point.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs9:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>Vivo X80 Pro – Outstanding cameras</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/06/vivo_x80_pro_review.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>Vivo has knocked it out of the park with the X80 Pro, a phone whose camera is truly excellent, rivalling the best Apple, Samsung, and Google have to offer</li><br><li style='font-size:22px;'>A Snapdragon 8 Gen 1 chip powers four rear lenses, the main being a wonderfully capable 50Mp sensor</li><br><li style='font-size:22px;'>Every lens benefits from Vivo’s V1+ image processing chip, and there’s gimbal stabilisation on the telephoto lens to aid clarity of zoom shots</li><br><li style='font-size:22px;'>It’s an incredibly full feature set, and low-light photography is outstanding</li><br><li style='font-size:22px;'>Add to that excellent video modes with cinema-wide aspect ratios and a film-like grain and you’ve got a powerhouse camera in your pocket</li><br><li style='font-size:22px;'>The phone is a big one so you’ll have to be happy with a 6.78in AMOLED</li><br><li style='font-size:22px;'>It’s a 120Hz LTPO (with variable refresh rate) and QHD+ resolution</li><br><li style='font-size:22px;'>Downsides to the phone are the lack of Gorilla Glass for proven scratch and crack protection to the front and back, and the frustrating software</li><br><li style='font-size:22px;'>But overall this is another leap forward for Vivo that you should seriously consider if you want a premium camera on the back of your phone.</ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)

with tabs10:

    st.markdown("<br><h1 style='text-align: center; color : #E8570E; font-size:50px'>Asus Zenfone 9 – Smallest premium Android</h1><br><br>", unsafe_allow_html=True)
    st.markdown(f"""<img src="https://b2c-contenthub.com/wp-content/uploads/2022/07/Asus-Zenfone-9_review.jpg?quality=50&strip=all" style="display: block; margin-left: 100px; margin-right: 100px; width:50%; height:50%; object-fit: cover; display: block; margin-right: auto; margin-left:auto">""", unsafe_allow_html=True)

    st.markdown("<br><br><br><br><ul><li style='font-size:22px;'>If you want a genuinely small Android phone with flagship level specs, then this is the phone for you.</li><br><li style='font-size:22px;'>It’s more premium – and physically smaller – than the Google Pixel 6a, but packs in a better chipset, amazingly good battery life for a phone of its size, and very good cameras.</li><br><li style='font-size:22px;'>Bravo, Asus</li><br><li style='font-size:22px;'>The back is not glass but instead a plastic composite that feels a little like textured paper.</li><br><li style='font-size:22px;'>There’s no wireless charging here, but you might prefer the fact your phone is more durable instead.</li><br><li style='font-size:22px;'>Camera-wise, you get a 50Mp main sensor which is very good and even has gimbal stabilisation that means this phone punches above its weight with suerb low-light photos and stable video.</li><br><li style='font-size:22px;'>We couldn’t believe how much Asus has stuffed into such a tiny phone, though we did find that the hadnset runs slightly hot at times.</li><br><li style='font-size:22px;'>If you don’t mind that, along with the fact Asus is only promising to update the software for two years, then you’ll love the little Zenfone 9, one of the last truly pocketable smartphones around.</li></ul>", unsafe_allow_html=True)
    st.markdown("<hr>",unsafe_allow_html=True)
